runtime: python37
env_variables:
  FLASK_APP: "main.py"
  AWS_REGION: "us-east-1"
  AWS_SESSION_TOKEN: "FwoGZXIvYXdzEMP//////////wEaDEcAiFoXTGFZj4GRmCLFAa1yFIfSgB9tc8wVt9WLr5WB6ili20LIHMOWV5P5p2SstwGWKEvtCe0kTsMAshkbcSSiYIJ+R82LKM/oJO6y3TiT+VBtTcWnvDi8ciiN1zLzaCyQCY4SxgDZMhoXsDfbTH752m8SkF12LqdnUsirr6xGSsH+4aspFDs+qUKotzmcNeUkuLe7US7imc/EKy7mz6k7lkJr9ICnUfPHi8ZUjM4a4Tmk4/GXNWWsaULrolO877Q1BmXQo/wn5QsYfnn87NDeVLJyKKCbi6IGMi1m7PM0HzW/lKnEMq2vJLOmdOpmI+vyFFzLTPT9vdpaGEwzrLMxA2+x/4T7GyI="
  AWS_ACCESS_KEY_ID: "ASIA2DEPGKPYZ62AR5Q3"
  AWS_SECRET_ACCESS_KEY: "L0UMCR+DuRZqm8knx7sCKpW7fpxlBmQIfeHbI28A"
